project:
  type: website
  output-dir: docs

website:
  title: "Final project"
  navbar:
    left:
      - href: index.qmd
        text: Introduction
      - Packages Required.qmd
      - Data Preparation.qmd
      - EDA.qmd
      - Summary.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    





